### ISSUE TITLE
Hp Chromebook 14a No Sound

### ISSUE THREAD

**Issue by DarkUmbre** [MilkyDeveloper/cb-linux#42] opened 2022-01-19 18:26 UTC
The model number is: C2B-A6H-D2K-T3R-M2Q-A4C
Board Name: octopus
Platform: Gemini Lake

**Comment by MilkyDeveloper** [comment] 2022-01-19 20:27
Duplicate of #22

**Closed by MilkyDeveloper** 2022-01-19 20:27 UTC
